/* Auto-generated with RNROLCompiler V2.7.0.0 don't edit */
#include "_RO_ObjectNetworking.h"
#ifdef _WIN32
#pragma warning(disable : 4786)
#endif
#include "../vrc_objectnetworking.h"

using namespace vrc;
_RO_DO_STD_FRAMEWORK(ObjectNetworking)
#include "RNReplicaNet/Inc/DataBlock_Function.h"
_RO_DO_MEMBERFUNC_PRESTAGE_DEF(ObjectNetworking,RPC_RequestUse)
unsigned int /*clientID*/  value1
_RO_DO_MEMBERFUNC_PRESTAGE(RPC_RequestUse)
_RO_DO_MEMBERFUNC_ADDVAR2(value1,unsigned int /*clientID*/ )
_RO_DO_MEMBERFUNC_POSTSTAGE(RPC_RequestUse)
_RO_DO_MEMBERFUNC_CRACK_START(ObjectNetworking,RPC_RequestUse)
unsigned int value1;
_RO_DO_MEMBERFUNC_MESSAGE_CRACK(value1)
_RO_DO_MEMBERFUNC_CRACK_END(ObjectNetworking,RPC_RequestUse)
value1
_RO_DO_MEMBERFUNC_CRACK_END2()
_RO_DO_MEMBERFUNC_PRESTAGE_DEF(ObjectNetworking,RPC_Use)
unsigned int /*clientID*/  value1
_RO_DO_MEMBERFUNC_PRESTAGE(RPC_Use)
_RO_DO_MEMBERFUNC_ADDVAR2(value1,unsigned int /*clientID*/ )
_RO_DO_MEMBERFUNC_POSTSTAGE(RPC_Use)
_RO_DO_MEMBERFUNC_CRACK_START(ObjectNetworking,RPC_Use)
unsigned int  value1;
_RO_DO_MEMBERFUNC_MESSAGE_CRACK(value1)
_RO_DO_MEMBERFUNC_CRACK_END(ObjectNetworking,RPC_Use)
value1
_RO_DO_MEMBERFUNC_CRACK_END2()
#include "RNReplicaNet/Inc/DataBlock_NData.h"
_RO_DO_BEGINREGISTERDATABLOCKS(ObjectNetworking)
_RO_DO_REGISTERBLOCK_FUNCTION_VAR(RPC_RequestUse)
_RO_DO_DATABLOCK_MAKERELIABLE()
_RO_DO_REGISTERBLOCK_END()
_RO_DO_REGISTERBLOCK_FUNCTION_VAR(RPC_Use)
_RO_DO_DATABLOCK_MAKERELIABLE()
_RO_DO_REGISTERBLOCK_END()
_RO_DO_REGISTERBLOCK_NDATA_VAR(_objectID)
_RO_DO_DATABLOCK_MAKERELIABLE()
_RO_DO_REGISTERBLOCK_END()
_RO_DO_REGISTERBLOCK_NDATA_VAR(_p_meshFile)
_RO_DO_DATABLOCK_MAKERELIABLE()
_RO_DO_REGISTERBLOCK_END()
_RO_DO_REGISTERBLOCK_NDATA_VAR(_positionX)
_RO_DO_DATABLOCK_MAKERELIABLE()
_RO_DO_REGISTERBLOCK_END()
_RO_DO_REGISTERBLOCK_NDATA_VAR(_positionY)
_RO_DO_DATABLOCK_MAKERELIABLE()
_RO_DO_REGISTERBLOCK_END()
_RO_DO_REGISTERBLOCK_NDATA_VAR(_positionZ)
_RO_DO_DATABLOCK_MAKERELIABLE()
_RO_DO_REGISTERBLOCK_END()
_RO_DO_REGISTERBLOCK_NDATA_VAR(_rotationZ)
_RO_DO_DATABLOCK_MAKERELIABLE()
_RO_DO_REGISTERBLOCK_END()
_RO_DO_REGISTERBLOCK_NDATA_VAR(_maxPickDistance)
_RO_DO_DATABLOCK_MAKERELIABLE()
_RO_DO_REGISTERBLOCK_END()
_RO_DO_REGISTERBLOCK_NDATA_VAR(_maxHeighlightDistance)
_RO_DO_DATABLOCK_MAKERELIABLE()
_RO_DO_REGISTERBLOCK_END()
_RO_DO_ENDREGISTERDATABLOCKS(ObjectNetworking)
